USE CineBook;

SELECT
    b.Booking_ID,
    c.Name AS Customer_Name,
    b.Total_Amount
FROM Bookings b
JOIN Customers c
    ON b.Customer_ID = c.Customer_ID;




SELECT
    b.Booking_ID,
    c.Name AS Customer_Name,
    m.Title AS Movie_Name,
    b.Seats_Booked,
    b.Total_Amount
FROM Bookings b
JOIN Customers c
    ON b.Customer_ID = c.Customer_ID
JOIN Shows s
    ON b.Show_ID = s.Show_ID
JOIN Movies m
    ON s.Movie_ID = m.Movie_ID;



-- Display details of all movie shows along with their respective movie, theatre, and screen information.
SELECT
    m.Title AS Movie_Name,
    t.Theatre_Name,
    sc.Screen_Name,
    s.Show_Date,
    s.Show_Time,
    s.Ticket_Price
FROM Shows s
JOIN Movies m
    ON s.Movie_ID = m.Movie_ID
JOIN Screens sc
    ON s.Screen_ID = sc.Screen_ID
JOIN Theatres t
    ON sc.Theatre_ID = t.Theatre_ID;


-- Q4. Display complete booking details including
-- customer, movie, theatre, screen, show, and payment information.

SELECT
    b.Booking_ID,
    c.Name AS Customer_Name,
    m.Title AS Movie_Name,
    t.Theatre_Name,
    sc.Screen_Name,
    s.Show_Date,
    s.Show_Time,
    b.Seats_Booked,
    b.Total_Amount,
    b.Booking_Status,
    p.Payment_Method,
    p.Payment_Status
FROM Bookings b
JOIN Customers c
    ON b.Customer_ID = c.Customer_ID
JOIN Shows s
    ON b.Show_ID = s.Show_ID
JOIN Movies m
    ON s.Movie_ID = m.Movie_ID
JOIN Screens sc
    ON s.Screen_ID = sc.Screen_ID
JOIN Theatres t
    ON sc.Theatre_ID = t.Theatre_ID
JOIN Payments p
    ON b.Booking_ID = p.Booking_ID;

-- Q5. Display total bookings and total revenue
-- generated by each theatre.

SELECT
    t.Theatre_Name,
    COUNT(b.Booking_ID) AS Total_Bookings,
    SUM(b.Total_Amount) AS Total_Revenue
FROM Bookings b
JOIN Shows s
    ON b.Show_ID = s.Show_ID
JOIN Screens sc
    ON s.Screen_ID = sc.Screen_ID
JOIN Theatres t
    ON sc.Theatre_ID = t.Theatre_ID
GROUP BY t.Theatre_Name
ORDER BY Total_Revenue DESC;


-- Q6. Display customer booking history
-- with movie name and booking amount.

SELECT
    c.Name AS Customer_Name,
    m.Title AS Movie_Name,
    b.Booking_Date,
    b.Seats_Booked,
    b.Total_Amount,
    b.Booking_Status
FROM Bookings b
JOIN Customers c
    ON b.Customer_ID = c.Customer_ID
JOIN Shows s
    ON b.Show_ID = s.Show_ID
JOIN Movies m
    ON s.Movie_ID = m.Movie_ID
ORDER BY c.Name, b.Booking_Date;


----------------------------------------------------------------
    
-- Q4. Display customer, movie, theatre and booking details.
SELECT
    b.Booking_ID,
    c.Name AS Customer_Name,
    m.Title AS Movie_Name,
    t.Theatre_Name,
    b.Total_Amount
FROM Bookings b
JOIN Customers c
    ON b.Customer_ID = c.Customer_ID
JOIN Shows s
    ON b.Show_ID = s.Show_ID
JOIN Movies m
    ON s.Movie_ID = m.Movie_ID
JOIN Screens sc
    ON s.Screen_ID = sc.Screen_ID
JOIN Theatres t
    ON sc.Theatre_ID = t.Theatre_ID;
    





SELECT * FROM Booking_Details;

SHOW INDEX FROM Movies;

